### PR TITLE
Fix symlink to IDEA installation directory

### PR DESCRIPTION
**Pull request by l0b0**
This closes issue #12 upstream.

### CODE REVIEW

**Comment by dkerwin** [comment]
Hey @l0b0,

thanks for your PR. Would you be willing to fix the errors that cause Travis to fail? 

Cheers!
Daniel

**Comment by l0b0** [comment]
Do you have a link to the issue? All I could see were puppet-lint issues
not related to my change.

Cheers
Victor

**Comment by l0b0** [comment]
Do you have any update on this?

**Comment by l0b0** [comment]
All tests passed after excluding non-supported versions of Ruby and excluding third party modules from linting.

**Comment by l0b0** [comment]
Ping?

**Comment by l0b0** [comment]
I'm no longer using puppet-idea (or Puppet for that sake, Nix FTW :wink:), and this looks like it's not going to get merged, so I'll just close it for neatness. Feel free to reopen if you want to merge it.

**Pull request closed without merging**
